language: php

php:
  - 7.2

services:
  postgresql

addons:
  postgresql: "10.4"

before_script:
  - cp .env.travis .env
  - psql -c 'create database myrecipes-test;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit
